# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = '2025.10.14.post1.dev23+g3183d9848.d20260502'
__version_tuple__ = version_tuple = (2025, 10, 14, 'post1', 'dev23', 'g3183d9848.d20260502')

__commit_id__ = commit_id = None
